# Generated by Django 5.1.7 on 2025-03-06 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique_for_date='student')),
                ('description', models.TextField()),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('lecturer_comment', models.TextField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
